---
- hosts: all
  becomes: yes 
  tasks: 
  - name: install webserver on ubuntu ansible node
     apt: 
        name: apache2
        state: present

  - name: start webserver on ubuntu ansible nodes 
    service:
              name: apache2
              state: started  

